# Generated by Django 2.1 on 2025-06-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mdfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='文書データ')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='pdfurl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'mdfiles',
            },
        ),
    ]
