# Generated by Django 2.1 on 2025-06-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdfile',
            old_name='text',
            new_name='base_text',
        ),
        migrations.AddField(
            model_name='mdfile',
            name='html_text',
            field=models.TextField(default='', verbose_name='htmlデータ'),
            preserve_default=False,
        ),
    ]
