# Generated by Django 5.2.3 on 2025-06-15 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdapp', '0002_alter_mdfile_title_mdfile_unique_title_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
