# Generated by Django 2.1 on 2025-06-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdapp', '0002_auto_20250612_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdfile',
            name='title',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='ファイル名'),
            preserve_default=False,
        ),
    ]
