# Generated by Django 5.2.3 on 2025-06-15 07:31

import mdapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdapp', '0003_alter_mdfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdfile',
            name='id',
            field=models.CharField(default=mdapp.models.generate_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
