# Generated by Django 5.2.3 on 2025-06-17 02:37

import django.db.models.deletion
import mdapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdapp', '0005_rename_author_mdfile_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sher',
            fields=[
                ('id', models.CharField(default=mdapp.models.generate_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdapp.mdfile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
