# Generated by Django 5.2.3 on 2025-06-17 02:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdapp', '0006_sher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sher',
            new_name='Share',
        ),
    ]
