# Generated by Django 5.2.3 on 2025-06-17 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdapp', '0007_rename_sher_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日時'),
            preserve_default=False,
        ),
    ]
